### ISSUE TITLE
[suggestion] Running this locally?

### ISSUE THREAD

**Issue by calebpanza** [sturdy-dev/codereview.gpt#1]
I would actually really love to be able to run this as a script on my machine _before_ submitting a PR as a gut check

**Comment by krlvi** [comment]
Thanks for the suggestion, I like it

**Comment by nickveenhof** [comment]
That would require submitting your patch file in the extension. Quite some work. Why not iterate and submit the PR, use the extension and iterate again? I'm not sure if it's useful enough to add support for it.

**Comment by nickveenhof** [comment]
I'm going to close this as I'm not sure how this could work with a chrome extension. I think it would be better to develop a CLI based git hook or so that before you submit it, it sends the code to OpenAI. Be careful, as you might be sending private code to an API that did not sign an NDA ;-)
