### ISSUE TITLE
Fails without giving any response or message, with quite big PRs

### ISSUE THREAD

**Issue by shamanthchandra-yb** [sturdy-dev/codereview.gpt#11]
Navigated to pull request and clicked on extension on chrome:

![Screenshot 2023-03-07 at 1 34 01 PM](https://user-images.githubusercontent.com/109518123/223361733-4ce691ad-8386-4d2a-8af9-4a46b08436cf.png)

**Comment by Araxeus** [comment]
> with quite big PRs

This happens on every PR I try – with 1 line, 10 lines, 100, etc

**Comment by nickveenhof** [comment]
See the Open PR #14 , it caps large PRs and uses proper APIs so it is less likely to fail

**Comment by nickveenhof** [comment]
This got merged, so should work. We can further optimize but at least it doesn't fail anymore
