### ISSUE TITLE
[Feature] Gitlab integration for self-hosted instances

### ISSUE THREAD

**Issue by thorewi** [sturdy-dev/codereview.gpt#15]
Hi,

is there a possibility to integrate this easily also into Gitlab? Thank you.

**Comment by nickveenhof** [comment]
If you compile from source it has support for GitLab.com

**Comment by krlvi** [comment]
I have started a release of `0.2.0` on the chrome web store, which has the contribution from @nickveenhof, hopefully it gets approved today.

We can make an issue for adding support for self hosted GitLab, wdyt @nickveenhof ?

**Comment by nickveenhof** [comment]
@krlvi yes, adding support for self-hosted GitLab makes a ton of sense. @thorewi can you create the issue? Thanks

**Comment by thorewi** [comment]
Hm, I guess you renamed this issue so everything is done for now and I don't have to do anything?

**Comment by nickveenhof** [comment]
> Hm, I guess you renamed this issue so everything is done for now and I don't have to do anything?

Yes. I'll pick this up asap.
