### ISSUE TITLE
How to use for hosted GitLab PR?

### ISSUE THREAD

**Issue by sbmaggarwal** [sturdy-dev/codereview.gpt#3]
How to use this for hosted GitLab PR?

**Comment by krlvi** [comment]
Hi, right now the plugin uses GitHub specific APIs, but I am sure that GitLab has equivalent ones. What is your use case? Happy to have a call and try to help

**Comment by krlvi** [comment]
@sbmaggarwal thanks to @nickveenhof there is now support for GitLab!

**Comment by sbmaggarwal** [comment]
Thanks a lot @nickveenhof and @krlvi.

I am still seeing this prompt though on my GitLab:
<img width="845" alt="Screenshot 2023-04-02 at 9 12 13 AM" src="https://user-images.githubusercontent.com/6919017/229330081-105cef63-4e05-417c-b8d8-31017a8a49a2.png">

I just freshly installed the extension. Anything I might be doing wrong?
