### ISSUE TITLE
Unable to enter API key

### ISSUE THREAD

**Issue by Sin-** [sturdy-dev/codereview.gpt#37]
Where do I enter the OpenAI API key?
You simply say to enter it in the extension options, but I can't find this option menu anywhere.

**Comment by nickveenhof** [comment]
It is available in the browser setting of the extension 

<img width="980" alt="image" src="https://github.com/sturdy-dev/codereview.gpt/assets/161341/780c2feb-7ac6-4ec2-ab99-95c7022b5dbf">

or

<img width="319" alt="image" src="https://github.com/sturdy-dev/codereview.gpt/assets/161341/46912ce7-55d0-4e33-8a75-6e41a56f793b">

**Comment by Sin-** [comment]
That's strange I don't have it...
I a mon brave so I tried on Google Chrome but same result...

<img width="677" alt="Capture d’écran 2023-05-25 à 14 41 39" src="https://github.com/sturdy-dev/codereview.gpt/assets/11181821/51e159c4-28e7-439e-842f-fb0a1de4f5ee">

**Comment by thibgn** [comment]
Same issue here 🤷

**Comment by SimoneGianni** [comment]
Same here

**Comment by nickveenhof** [comment]
@krlvi would you be able to push a new release out? it might be that the latest release doesn't have this?

**Comment by krlvi** [comment]
Okay, for the Chrome store I had to create a privacy policy (https://github.com/sturdy-dev/codereview.gpt/commit/84f8b36c1ecff4f01672e4ab2f0e6b16b5e87474) and resubmit it.

**Comment by krlvi** [comment]
okay v 0.3.0 is out, could you try again?

**Comment by Sin-** [comment]
All good! Thanks!
<img width="719" alt="Capture d’écran 2023-06-08 à 14 44 16" src="https://github.com/sturdy-dev/codereview.gpt/assets/11181821/f07fa614-3aa0-441d-91af-0ec90500b7db">
