### ISSUE TITLE
Fails with big PR-s 

### ISSUE THREAD

**Issue by wolasss** [sturdy-dev/codereview.gpt#4]
If there are many files na changes in the PR (for me it fails with +256 −41 PR), GPT fails with the message:

```
{"message":"The message you submitted was too long, please reload the conversation and submit something shorter.","code":"message_length_exceeds_limit"}
```

Maybe it would be useful to split the patch changes and send separate requests for each change?

**Comment by nickveenhof** [comment]
This should no longer be an issue with https://github.com/sturdy-dev/codereview.gpt/pull/14 merged
