### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by MirzaCickusic** [sturdy-dev/codereview.gpt#5]
Whatever I try I'll be getting: _Please login at [chat.openai.com](https://chat.openai.com/) first._ 

<img width="690" alt="image" src="https://user-images.githubusercontent.com/56160169/211586742-d73f5f2c-f21b-4625-924b-484255d3ae65.png">

**Comment by calebpanza** [comment]
+1

**Comment by haoran0412** [comment]
+1

**Comment by wieseljonas** [comment]
Same

**Comment by rafanimal** [comment]
Even after logging in, it still doesn't work.

**Comment by nickveenhof** [comment]
This should no longer be an issue with https://github.com/sturdy-dev/codereview.gpt/pull/14 merged

**Comment by Torantulino** [comment]
I'm currently getting this issue - was working fine before a day or so ago.
