### ISSUE TITLE
Fails with no details on the cause of the failure

### ISSUE THREAD

**Issue by Alan-Jowett** [sturdy-dev/codereview.gpt#6]
![image](https://user-images.githubusercontent.com/20480683/214483195-ff33bc31-bf3a-4b70-80ce-984e6a431df4.png)

Is there somewhere I can get more info on why it's failing?

**Comment by chhs2131** [comment]
![image](https://user-images.githubusercontent.com/10378777/215322300-1352f195-d67f-43ce-82d4-a77d08493525.png)

I have the same problem. The repository used for tested is `public`.

**Comment by ashwinkhadgi** [comment]
@nickveenhof I am also getting the same error looks like the below API is failed
https://chat.openai.com/backend-api/conversation
{
"detail": "Method Not Allowed"
}
