### ISSUE TITLE
Review is getting stuck after few sentences

### ISSUE THREAD

**Issue by ElisarEisenbach** [sturdy-dev/codereview.gpt#7]
It seems like it's starting the review, but after 2/3 sentences it continue with loading and stops generating text
![Screen Shot 2023-01-25 at 10 56 39](https://user-images.githubusercontent.com/62891625/214520448-2590635b-6dcf-474a-a51d-d18b8d03c217.png)

**Comment by diegopamio** [comment]
I'm having the same issue, and the console of the popup window shows an error:
```
Uncaught (in promise) SyntaxError: Unexpected non-whitespace character after JSON at position 4
    at JSON.parse (<anonymous>)
```

**Comment by ct3685** [comment]
I'm having the same issue. 😔 This is an awesome extension though! Just gotta get the bugs like this one worked out and it will be even better!
